language: java
sudo: false
dist: trusty
script: ant jar
jdk: oraclejdk8
before_deploy:
  - zip -r jaer-dist.zip jAERViewer_linux.sh jAERViewer_win64.exe SplashScreen.gif dist/ jars/ lib/ biasgenSettings/ filterSettings/ images/ sounds/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: jaer-dist.zip
  skip_cleanup: true
  on:
    tags: true
